baseURL = "/"
languageCode = "en-gb"
title = "The Spinney"
theme = "spinney"
[params]
  bookingLink = "https://www.booking.com/hotel/gb/the-spinney-leamington-spa.en-gb.html"
  airbnbLink = "https://www.airbnb.co.uk/rooms/29297535"
[menu]

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"

